name: No broken dependency
description: Action for detecting broken package-lock.json.
branding:
  icon: alert-circle
  color: red
inputs:
  directory:
    default:
runs:
  using: composite
  steps:
    - run: |
        git fetch --depth=10000 origin "${{github.base_ref}}"
        git fetch --depth=10000 origin "${{github.head_ref}}"

        if [ "$(git diff 'origin/${{github.base_ref}}...origin/${{github.head_ref}}' --name-only)" = "${{inputs.directory}}package-lock.json" ]; then
          exit
        fi;

        git restore -s "origin/${{github.base_ref}}...origin/${{github.head_ref}}" "${{inputs.directory}}package-lock.json"

        npm install --package-lock-only

        git diff --exit-code "${{inputs.directory}}package-lock.json"
      shell: bash
