name: No broken dependency
description: Action for detecting broken package-lock.json.
branding:
  icon: alert-circle
  color: red
inputs:
  default-branch:
    default: main
runs:
  using: composite
  steps:
    - run: |
        git fetch --unshallow origin "${{inputs.default-branch}}"

        if [ "$(git diff 'origin/${{inputs.default-branch}}'... --name-only)" = "package-lock.json" ]; then
          exit
        fi;

        git restore -s "origin/${{inputs.default-branch}}..." package-lock.json

        npm install --package-lock-only

        git diff --exit-code package-lock.json
      shell: bash
