name: No broken dependency
description: Action for detecting broken package-lock.json.
branding:
  icon: alert-circle
  color: red
inputs:
  default-branch:
    default: main
  directory:
    default:
runs:
  using: composite
  steps:
    - run: |
        git fetch --depth=10000 origin "${{inputs.default-branch}}"

        if [ "$(git diff 'origin/${{inputs.default-branch}}'... --name-only)" = "${{inputs.directory}}package-lock.json" ]; then
          exit
        fi;

        git restore -s "origin/${{inputs.default-branch}}..." "${{inputs.directory}}package-lock.json"

        npm install --package-lock-only

        git diff --exit-code "${{inputs.directory}}package-lock.json"
      shell: bash
