inputs:
  default-branch:
    default: main
runs:
  using: composite
  steps:
    - run: git fetch origin ${{inputs.default-branch}}
      shell: bash
    - run: git restore -s origin/${{inputs.default-branch}} package-lock.json
      shell: bash
    - run: npm install --package-lock-only
      shell: bash
    - run: git diff --exit-code package-lock.json
      shell: bash
